### ISSUE TITLE
Slide is reset if the window is resized

### ISSUE THREAD

**Issue by floatingdino** [meandmax/lory#650] opened 2017-04-18 06:05 UTC
When resizing the window, the slider returns to the translate value for the first slide.
Observed on macOS 10.12.1 / Chrome 57 on sliders with % widths.

**Comment by mciastek** [comment] 2017-05-16 11:52
It's caused by `reset` method in resize event callback. First of all, I would like to set if I want slider to reset after resize. Secondly, it would be better to listen to `orientationchange` on mobile devices, because normal scrolling (and hiding browser's top bar) triggers `resize` event.

@meandmax Is that library still maintained?

**Comment by felipearosemena** [comment] 2017-06-15 13:39
@floatingdino @mciastek  I was able to address part of the issue on mobile by adding the following into the `onResize` function in the plugin:

```
function onResize (event) {

        if(window.innerWidth == wWidth) {
            return;
        } else {
            wWidth = window.innerWidth;
        }

        reset();

        dispatchSliderEvent('on', 'resize', {
            event
        });
    }
```

and defined `wWidth` at the top near `lory`'s definition:
```
    let index   = 0;
    let options = {};
    let wWidth  = window.innerWidth;
```

@meandmax Would this be something that should be merged into the repo?

**Comment by nstanard** [comment] 2017-06-28 18:52
@mciastek 

> on mobile devices, because normal scrolling (and hiding browser's top bar) triggers resize event

The reason some mobile devices fire a resize event is because of the URL bar that animates into view. This does not mean that all mobile devices behave this way.

**Comment by nstanard** [comment] 2017-06-28 18:55
![image](https://user-images.githubusercontent.com/4204806/27654983-59e7ee0e-5c09-11e7-94ce-a1b638b5c35e.png)

The last feature Max has added is an option to turn rewind on resize off. You can use that and add your own rewind behavior on top of the slider.

**Closed by nstanard** 2017-06-28 18:55 UTC

**Comment by VitorLuizC** [comment] 2017-06-30 21:13
@nstanard
This issue should be reopen because `rewindOnResize` should not be used with `infinite: true` which is my current implementation. Also, this reset not fires the `'after.lory.slide'` event.
