### ISSUE TITLE
Browserify require

### ISSUE THREAD

**Issue by baptooo** [meandmax/lory#126] opened 2015-11-23 10:11 UTC
Hello @meandmax, I have noticed an issue when importing the library on browserify.

As the "main" property in package.json refers to "dist/lory.js", there is a wrapper on the library apparently and the module imported looks like this,

    {
        __esModule: true,
        lory: function() { ... }
    }

I moved back to v1.2.6 which works fine actually.

Thank you very much !

**Comment by meandmax** [comment] 2015-12-16 12:34
This could be actually a bug caused by the update to babel6 .. Have u tried to import the module like the following: 

```
import {lory} from 'lory.js'
```

Sorry for this breaking change! That was not my intend.

Max

**Comment by meandmax** [comment] 2015-12-16 12:35
This issue will be fixed by

https://github.com/meandmax/lory/issues/148

**Closed by meandmax** 2015-12-16 12:35 UTC
