### ISSUE TITLE
lory slider Cannot read property 'CustomEvent' of undefined

### ISSUE THREAD

**Issue by SteveQ88** [meandmax/lory#641] opened 2017-04-07 12:57 UTC
Hi I am using browserify and babel with gulp as my setup, I recently changed from grunt and have used lory slider many times but I have come across this error 

lory slider Cannot read property 'CustomEvent' of undefined

which points to line 723 in lory.js ...

 /* WEBPACK VAR INJECTION */(function(global) {
	var NativeCustomEvent = global.CustomEvent;

i am requiring lory like so ...
var lory =  require('lory.js').lory;

and initialising it like so 
var multiSlides = document.querySelector('.js_multislides');
    lory(multiSlides, {
        infinite: 4,
        slidesToScroll: 4
    });

Please could you give me some pointers if this is not an issue with lory?
Kind Regards

Steve

.....
Uncaught TypeError: Cannot read property 'CustomEvent' of undefined
    at Object.<anonymous> (lory.js:724)
    at Object.defineProperty.value (lory.js:772)
    at __webpack_require__ (lory.js:30)
    at Object.NativeCustomEvent (lory.js:696)
    at __webpack_require__ (lory.js:30)
    at Object.defineProperty.value (lory.js:78)
    at __webpack_require__ (lory.js:30)
    at Object.defineProperty.value (lory.js:57)
    at __webpack_require__ (lory.js:30)
    at lory.js:50

**Comment by Ficik** [comment] 2017-05-02 16:08
I've just hit into same problem when bundling with rollup + babel from npm. 

`import {lori} from "lori.js/src/lori.js"` complains about "custom-event" being external dependency and fails in runtime with  `Cannot read property 'CustomEvent' of undefined`

**`custom-event` should be `dependency` not devDependency**

**Comment by jeroenbraspenning** [comment] 2017-05-12 05:55
I've fixed this locally by removing the first line of the 'dispatch-event.js' this file was referencing itself.

`import CustomEvent from './dispatch-event'
`

**Comment by VitorLuizC** [comment] 2017-06-14 16:46
You should exclude `node_modules` folder from your bundler script.

On webpack:
```js
...
module: {
  rules: [
    {
      test: /\.js$/,
      exclude: /(node_modules)/, // <-- include this line
      use: 'babel-loader'
    }
  ]
}
...
```

**Comment by chaucerbao** [comment] 2017-06-18 06:46
I ran into this issue while using only Babel (no webpack nor Browserify) with [babel-preset-env](https://github.com/babel/babel-preset-env).

I believe the problem is with the code injected to transform module syntax (the umd), where [global](https://github.com/meandmax/lory/blob/master/dist/lory.js#L724) was being resolved to `undefined` when it should have been resolved to `window` in the browser.

Disabling the transformation fixed it for me.
```
{
  presets: [
    ['env', { modules: false }]
  ]
}
```

I know this solution may not work for you because you actually __need__ module imports, but this worked for my situation, and may be a step to finding the deeper issue.

**Comment by davidrhoden** [comment] 2017-06-22 21:28
chaucerbao: where do you put the code you pasted to disable the transformation?

**Comment by chaucerbao** [comment] 2017-06-23 02:13
That goes into the [Babel config file](https://babeljs.io/docs/usage/babelrc/#lookup-behavior), wherever you might have it (`.babelrc` or `package.json`).

**Comment by nstanard** [comment] 2017-06-28 19:10
@Ficik You're importing the source file... not the distribution file... So basically you're importing the file intended for local environment development.

**Comment by nstanard** [comment] 2017-06-28 19:11
@SteveQ88 I'm closing this for now. But I will be testing out lory with Rollup an other build tools in the near future. If I find that this is really an issue I will re-open it.

**Closed by nstanard** 2017-06-28 19:11 UTC

**Comment by andreasvirkus** [comment] 2017-07-31 14:21
I'd like this issue to be reopened. Using Lory with Webpack and `vue-ssr-webpack-plugin`.
As you can see, the error occurs in the distribution file (`lory.js/dist/lory.js`):
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'CustomEvent' of undefined
    at Object.<anonymous> (/Users/andreas.virkus/code/skin/node_modules/lory.js/dist/lory.js:724:32)
    at Object.defineProperty.value (/Users/andreas.virkus/code/skin/node_modules/lory.js/dist/lory.js:772:31)
    at __webpack_require__ (/Users/andreas.virkus/code/skin/node_modules/lory.js/dist/lory.js:30:30)
    at Object.NativeCustomEvent (/Users/andreas.virkus/code/skin/node_modules/lory.js/dist/lory.js:696:21)
    at __webpack_require__ (/Users/andreas.virkus/code/skin/node_modules/lory.js/dist/lory.js:30:30)
    at Object.defineProperty.value (/Users/andreas.virkus/code/skin/node_modules/lory.js/dist/lory.js:78:23)
    at __webpack_require__ (/Users/andreas.virkus/code/skin/node_modules/lory.js/dist/lory.js:30:30)
    at Object.defineProperty.value (/Users/andreas.virkus/code/skin/node_modules/lory.js/dist/lory.js:57:19)
    at __webpack_require__ (/Users/andreas.virkus/code/skin/node_modules/lory.js/dist/lory.js:30:30)
    at /Users/andreas.virkus/code/skin/node_modules/lory.js/dist/lory.js:50:18
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `babel-node --presets es2015,stage-0 --use_strict server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by MartinMuzatko** [comment] 2017-09-10 11:19
I can confirm, I'm also requiring the dist file. Also, it complained about stage-0 being not preset.

Using `modules: false` does not work:
```js
ERROR in ./src/main.js
Module build failed: ReferenceError: [BABEL] /Users/martinmuzatko/dev/github/s-s-f.de/src/main.js: Using removed Babel 5 option: base.modules - Use the corresponding module transform plugin in the `plugins` option. Check out http://babeljs.io/docs/plugins/#modules
    at Logger.error (/Users/martinmuzatko/dev/github/s-s-f.de/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/martinmuzatko/dev/github/s-s-f.de/node_modules/babel-core/lib/transformation/file/options/option-manager.js:220:20)
    at OptionManager.init (/Users/martinmuzatko/dev/github/s-s-f.de/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/martinmuzatko/dev/github/s-s-f.de/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/martinmuzatko/dev/github/s-s-f.de/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/martinmuzatko/dev/github/s-s-f.de/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/martinmuzatko/dev/github/s-s-f.de/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/martinmuzatko/dev/github/s-s-f.de/node_modules/babel-loader/lib/index.js:163:20)
```

**Comment by opr** [comment] 2017-09-12 14:20
Also suffering from this dreadful issue

`import {lory} from '../../../vendor/lory/lory.min.js';
export default class TestimonialSlider {

    constructor() {
        document.addEventListener('DOMContentLoaded', () => {
           let testimonialPanel = document.getElementsByClassName('testimonial-slider');

           if(testimonialPanel.length > 0) {
               lory(testimonialPanel, {});
           }
        });
    }
}`

`Uncaught TypeError: Cannot read property 'CustomEvent' of undefined
    at Object.eval (lory.min.js?9bd3:1)
    at Object.defineProperty.value (lory.min.js?9bd3:1)
    at t (lory.min.js?9bd3:1)
    at Object.i (lory.min.js?9bd3:1)
    at t (lory.min.js?9bd3:1)
    at Object.defineProperty.value (lory.min.js?9bd3:1)
    at t (lory.min.js?9bd3:1)
    at Object.defineProperty.value (lory.min.js?9bd3:1)
    at t (lory.min.js?9bd3:1)
    at eval (lory.min.js?9bd3:1)`

**Comment by Oliv** [comment] 2017-11-16 13:13
Hello there, 
importing dist version fails with babel : 

`Uncaught TypeError: Cannot read property 'CustomEvent' of undefined
    at Object.<anonymous> (lory.js:775)
    at Object.defineProperty.value (lory.js:823)
    at __webpack_require__ (lory.js:37)
    at Object.NativeCustomEvent (lory.js:744)
    at __webpack_require__ (lory.js:37)
    at Object.defineProperty.value (lory.js:95)
    at __webpack_require__ (lory.js:37)
    at Object.defineProperty.value (lory.js:66)
    at __webpack_require__ (lory.js:37)
    at lory.js:58
(anonymous) @ lory.js:775
Object.defineProperty.value @ lory.js:823
__webpack_require__ @ lory.js:37
NativeCustomEvent @ lory.js:744
__webpack_require__ @ lory.js:37
Object.defineProperty.value @ lory.js:95
__webpack_require__ @ lory.js:37
Object.defineProperty.value @ lory.js:66
__webpack_require__ @ lory.js:37
(anonymous) @ lory.js:58
(anonymous) @ lory.js:60
webpackUniversalModuleDefinition @ lory.js:10
(anonymous) @ lory.js:16
(anonymous) @ lory.js:939
initModule @ app.js:42
require @ app.js:59
expanded @ app.js:34
(anonymous) @ page.definitions.js:26
initModule @ app.js:42
require @ app.js:59
expanded @ app.js:34
(anonymous) @ app.js:12
initModule @ app.js:42
require @ app.js:59
expanded @ app.js:34
(anonymous) @ index.js:3
initModule @ app.js:42
require @ app.js:59
(anonymous) @ (index):21`

The solution I found is to `npm i custom-event` in my project, then import it before importing lory

`import CustomEvent from 'custom-event';
import { lory } from 'lory.js/src/lory.js';`

Still not clean, but works.
Regards
