### ISSUE TITLE
Bug: Slider resetting on all touch screen devices when scrolling

### ISSUE THREAD

**Issue by SukhKalsi** [meandmax/lory#493] opened 2016-11-10 11:04 UTC
Device: iPad Air 2 using iOS 10.0.1
Website: http://meandmax.github.io/lory/

On the Lory homepage, testing on the iPad I notice that when any slide is not on the first and you scroll, the slide for whatever reason resets itself to the first slide.

**Comment by SukhKalsi** [comment] 2016-11-23 12:55
I've noticed that this affects all touch screen devices. Affected on iOS (iPad & iPhone) and on Android (Chrome, and no doubt Android browsers too).

Any update as to whether this will be picked up? Almost been 2 weeks now since I have raised this yet there has been no acknowledgment of the issue.

**Comment by nstanard** [comment] 2016-11-28 18:39
Hey @SukhKalsi,

Are you able to pass in rewindOnResize as false through the options? I know some devices change the view size on scroll and if a resize event fires on the page the sliders will go back to the first slide by default.

**Comment by averest** [comment] 2016-12-01 16:10
I have exactly the same problem. Passing rewindOnResize: false doesn't fix the issue. Can anybody copy that?

**Comment by moklick** [comment] 2016-12-09 15:31
I had the same problem on iOS (10.x.x), and Android (6.x). The option `rewindOnResize: false` fixed it.

**Comment by averest** [comment] 2016-12-15 09:59
Does anybody have a fix for this. Would be highly appreciated... ;)

**Comment by moklick** [comment] 2016-12-15 12:01
We could fix it with options `{ infinite: false, rewindOnResize: false }`. `rewindOnResize` doesn't work when `infinite` is `true`. So it's important to set it to `false`

**Comment by marcelalburg** [comment] 2016-12-20 10:11
👍

**Comment by motoringcouk** [comment] 2016-12-20 13:15
I have a similar issue to this, which is triggered when i remove/add elements to the slider. I'm calling lory like this:
`
var slider = document.querySelector('.buying-mobile__container');
var inst = lory(slider, {
             infinite: false,
             rewindOnResize: false,
             rewind: true
});`

and calling `inst.setup();` when i have finished updating the dom.

any help would be appreciated.

**Comment by nstanard** [comment] 2016-12-20 15:12
@motoringcouk Please open your own issue ticket with a demo link highlighting the issue you are wanting to present.

**Comment by felipearosemena** [comment] 2017-06-15 13:40
I was able to address part of the issue on mobile by adding the following into the `onResize` function in the plugin:
```
function onResize (event) {

        if(window.innerWidth == wWidth) {
            return;
        } else {
            wWidth = window.innerWidth;
        }

        reset();

        dispatchSliderEvent('on', 'resize', {
            event
        });
    }
```
and defined `wWidth` at the top near `lory`'s definition:
```
    let index   = 0;
    let options = {};
    let wWidth  = window.innerWidth;
```

**Comment by nstanard** [comment] 2017-06-28 19:15
The original description is a feature, not a bug. Closing this.

**Closed by nstanard** 2017-06-28 19:15 UTC
